name: Update Thorium Ebuild

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-thorium:
    name: Update Thorium Ebuild

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v6

      - name: Update Thorium Ebuild
        shell: pwsh
        run: ./.scripts/Update-Thorium.ps1

      - name: Check for Changes
        id: check_changes
        shell: pwsh
        run: |
          if (Test-Path "ChangesMade") {
            "changes=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            Remove-Item "ChangesMade"
          } else {
            "changes=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "www-client/thorium-bin: update to latest version"
          title: "www-client/thorium-bin: update to latest version"
          body: "Automated update of Thorium Browser (binary version) triggered by new upstream release."
          branch: "update-thorium"
          delete-branch: true
